<?php

return [
    'city' => 'perm',
    'openauth_long' => array(
        'client_id' => 'SALE_AGENT',
        'city' => 'perm',
        'secret' => 'qazxswdbnfkbq-tial4421asdfgh',
        'grant_type' => 'password',
        'response_type$c' => 'wc_xml'
    ),
    // идентификаторы продуктов
    'services' => array(
        5 => 'Интернет',
        12 => 'Кабельное ТВ',
        32 => 'Цифровое ТВ',
        53 => 'Дом.ru TV',
        31 => 'Телефония'
    ),
    'devices' => array(
        1 => '9000',
        2 => 'DMT',
        3 => 'CAM'
    ),
    'cities' => array(
        'testing' => 'Тестинг',
        'testing2' => 'Тестинг2',
        'barnaul' => 'Барнаул',
        'bryansk' => 'Брянск',
        'volgograd' => 'Волгоград',
        'vlz' => 'Волжский',
        'voronezh' => 'Воронеж',
        'dzr' => 'Дзержинск',
        'ekat' => 'Екатеринбург',
        'izhevsk' => 'Ижевск',
        'iz' => 'Интерзет',
        'irkutsk' => 'Иркутск',
        'yola' => 'Йошкар-Ола',
        'kazan' => 'Казань',
        'kirov' => 'Киров',
        'krsk' => 'Красноярск',
        'kurgan' => 'Курган',
        'kursk' => 'Курск',
        'lipetsk' => 'Липецк',
        'mgn' => 'Магнитогорск',
        'chelny' => 'Набережные Челны',
        'nk' => 'Нижнекамск',
        'nn' => 'Нижний Новгород',
        'nsk' => 'Новосибирск',
        'omsk' => 'Омск',
        'oren' => 'Оренбург',
        'penza' => 'Пенза',
        'perm' => 'Пермь',
        'rostov' => 'Ростов-на-Дону',
        'ryazan' => 'Рязань',
        'samara' => 'Самара',
        'spb' => 'Санкт-Петербург',
        'saratov' => 'Саратов',
        'syzran' => 'Сызрань',
        'tver' => 'Тверь',
        'tomsk' => 'Томск',
        'tula' => 'Тула',
        'tmn' => 'Тюмень',
        'ulsk' => 'Ульяновск',
        'ufa' => 'Уфа',
        'cheb' => 'Чебоксары',
        'chel' => 'Челябинск',
        'engels' => 'Энгельс',
        'yar' => 'Ярославль',
    )
];